version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    reviewers:
      - "mikolajb"
    assignees:
      - "mikolajb"
    commit-message:
      prefix: "chore:"
